modLoader = "javafml"
loaderVersion = "[43,)"
issueTrackerURL = "https://github.com/EpicSquid/Whoosh/issues"
license = "MIT"
[[mods]]
modId = "whoosh"
version = "${file.jarVersion}"
displayName = "Whoosh"
displayURL = "https://minecraft.curseforge.com/projects/whoosh"
credits = "1.12.2 Version originally made by ImbaKnugel"
authors = "EpicSquid, Grinner117"
description = '''
Portable teleportation for Thermal
'''
[[dependencies.whoosh]]
modId = "forge"
mandatory = true
versionRange = "[43.2,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.whoosh]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.whoosh]]
modId = "thermal"
mandatory = false
versionRange = "[10.0,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.whoosh]]
modId = "kotlinforforge"
mandatory = true
versionRange = "[3.11.0,)"
ordering = "NONE"
side = "BOTH"